// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bootcamp_potencial_net_developer_dio_mvc.Context;

#nullable disable

namespace bootcamp_potencial_net_developer_dio_mvc.Migrations
{
  [DbContext(typeof(bootcamp_potencial_net_developer_dio_mvc.Context.Context))]
  [Migration("20221114000405_AdicionaTabelaContato")]
  partial class AdicionaTabelaContato
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "6.0.7")
          .HasAnnotation("Relational:MaxIdentifierLength", 64);

      modelBuilder.Entity("bootcamp_potencial_net_developer_dio_mvc.Models.Contato", b =>
          {
            b.Property<int>("ID")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            b.Property<bool>("Ativo")
                      .HasColumnType("tinyint(1)");

            b.Property<string>("Nome")
                      .HasColumnType("longtext");

            b.Property<string>("Telefone")
                      .HasColumnType("longtext");

            b.HasKey("ID");

            b.ToTable("Contatos");
          });
#pragma warning restore 612, 618
    }
  }
}
